name: h_ide
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc:
  bloc:
  equatable:
  resizable_widget: ^1.0.5
  window_manager: ^0.3.5
  hive:
  hive_flutter:
  google_fonts: ^5.1.0
  yaml: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
